---
- hosts: all
  become: true
  tasks:
    
  - name: update apt cache
    apt:
      update_cache: yes
        
  - name: install apache2 and php on Ubuntu
    apt: 
      name:
        - apache2
        - libapache2-mod-php
