---

- hosts: all
  become: true
  tasks:

  - name: update apt cache
    apt:
      update_cache: yes  

  - name: install apache
    apt:
      name: apache2
      state: absent 

  - name: install php support for apache
    apt:
      name: libapache2-mod-php    
      state: absent
